### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by BorisovskiP** [yireo/Yireo_ExtensionCheckerCli#1]
Hello @jissereitsma, we would like to use this module. 

Will a release be available soon ?

**Comment by jissereitsma** [comment]
There are no additional features scheduled here. I've simply released 0.0.1 as it is :)

**Comment by jissereitsma** [comment]
Ref https://packagist.org/packages/yireo/magento2-extensionchecker-cli

**Comment by BorisovskiP** [comment]
Thanks

**Comment by BorisovskiP** [comment]
@jissereitsma i just noticed you tagged a version, but didnt actually do a release. Was that intentional ?

**Comment by jissereitsma** [comment]
I've checked and it seems the GitHub API `releases` endpoint is now only creating a new tag, not a new release. While this is less than perfect, I'll leave it be for the moment, because the tag is the thing that is picked up by Packagist anyway. In other words, the focus is not to have a GitHub release, but to have a composer release.

**Comment by jissereitsma** [comment]
Ah, found it anyway. Tag 0.0.2 is now a GitHub release as well.
